projects:
  ninjachef:
    schemaPath: src/graphql/schema.json
    includes:
      - .js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
